[theme]
name = "catppuccin-mocha"

[colors]
AlertInfo  = "#89b4fa"
AlertWarn  = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#7f849c"
Base       = "#cdd6f4"
Title      = "#cba6f7"
Important  = "#fab387"
Guidance   = "#94e2d5"
