#!/usr/bin/env bash
# tools/discovery/scripts/10-brew.sh
# Snapshot Homebrew taps, leaf formulae, and casks into installed-brew.yaml.
# Read-only sensor: never installs, upgrades, or removes anything.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/log.sh
source "$SCRIPT_DIR/../lib/log.sh"
OUTPUT_DIR="$SCRIPT_DIR/../output"

mkdir -p "$OUTPUT_DIR"

TARGET="$OUTPUT_DIR/installed-brew.yaml"

write_empty_yaml() {
  local tmp
  tmp="$(mktemp "$OUTPUT_DIR/.installed-brew.yaml.XXXXXX")"
  {
    printf '%s\n' '# Generated by tools/discovery/scripts/10-brew.sh'
    printf '%s\n' '# Each entry has tags: [TODO]. Replace during review:'
    printf '%s\n' '#   []                  install always'
    printf '%s\n' '#   [optional, BUCKET]  declared but skipped by default'
    printf '%s\n' '#   [work] / [personal] conditional on machine type'
    printf '%s\n' '#   [manual]            tracked, never auto-installed'
    printf '%s\n' '#   [skip]              do not carry forward'
    printf '\n'
    printf '%s\n' 'taps: []'
    printf '\n'
    printf '%s\n' 'formulae: []'
    printf '\n'
    printf '%s\n' 'casks: []'
  } > "$tmp"
  mv "$tmp" "$TARGET"
}

if ! command -v brew >/dev/null 2>&1; then
  log_warn "brew not found; emitting empty installed-brew.yaml"
  write_empty_yaml
  log_ok "wrote $TARGET (empty)"
  exit 0
fi

log_info "collecting brew taps"
if ! taps_raw="$(brew tap 2>/dev/null)"; then
  log_error "brew tap failed"
  exit 1
fi

log_info "collecting brew leaves (top-level formulae)"
if ! leaves_raw="$(brew leaves 2>/dev/null)"; then
  log_error "brew leaves failed"
  exit 1
fi

log_info "collecting brew casks"
if ! casks_raw="$(brew list --cask 2>/dev/null)"; then
  log_error "brew list --cask failed"
  exit 1
fi

# Sort each list deterministically. Drop blank lines.
taps_sorted="$(printf '%s\n' "$taps_raw" | sed '/^[[:space:]]*$/d' | LC_ALL=C sort -u)"
leaves_sorted="$(printf '%s\n' "$leaves_raw" | sed '/^[[:space:]]*$/d' | LC_ALL=C sort -u)"
casks_sorted="$(printf '%s\n' "$casks_raw" | sed '/^[[:space:]]*$/d' | LC_ALL=C sort -u)"

tmp="$(mktemp "$OUTPUT_DIR/.installed-brew.yaml.XXXXXX")"

{
  printf '%s\n' '# Generated by tools/discovery/scripts/10-brew.sh'
  printf '%s\n' '# Each entry has tags: [TODO]. Replace during review:'
  printf '%s\n' '#   []                  install always'
  printf '%s\n' '#   [optional, BUCKET]  declared but skipped by default'
  printf '%s\n' '#   [work] / [personal] conditional on machine type'
  printf '%s\n' '#   [manual]            tracked, never auto-installed'
  printf '%s\n' '#   [skip]              do not carry forward'
  printf '\n'

  if [ -z "$taps_sorted" ]; then
    printf '%s\n' 'taps: []'
  else
    printf '%s\n' 'taps:'
    while IFS= read -r tap; do
      [ -z "$tap" ] && continue
      printf '  - %-45s # tags: [TODO]\n' "$tap"
    done <<< "$taps_sorted"
  fi
  printf '\n'

  if [ -z "$leaves_sorted" ]; then
    printf '%s\n' 'formulae: []'
  else
    printf '%s\n' 'formulae:'
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      printf '  - name: %s\n' "$f"
      printf '    tags: [TODO]\n'
    done <<< "$leaves_sorted"
  fi
  printf '\n'

  if [ -z "$casks_sorted" ]; then
    printf '%s\n' 'casks: []'
  else
    printf '%s\n' 'casks:'
    while IFS= read -r c; do
      [ -z "$c" ] && continue
      printf '  - name: %s\n' "$c"
      printf '    tags: [TODO]\n'
    done <<< "$casks_sorted"
  fi
} > "$tmp"

mv "$tmp" "$TARGET"

tap_count="$(printf '%s\n' "$taps_sorted" | sed '/^[[:space:]]*$/d' | wc -l | tr -d ' ')"
leaf_count="$(printf '%s\n' "$leaves_sorted" | sed '/^[[:space:]]*$/d' | wc -l | tr -d ' ')"
cask_count="$(printf '%s\n' "$casks_sorted" | sed '/^[[:space:]]*$/d' | wc -l | tr -d ' ')"

log_ok "wrote $TARGET (taps=$tap_count formulae=$leaf_count casks=$cask_count)"
