#!/usr/bin/env bash
# tools/discovery/scripts/50-mise-asdf.sh
# Snapshot installed and currently-active language runtimes managed by
# mise (preferred) or asdf into mise-asdf.yaml. Read-only sensor.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/log.sh
source "$SCRIPT_DIR/../lib/log.sh"
OUTPUT_DIR="$SCRIPT_DIR/../output"

mkdir -p "$OUTPUT_DIR"

TARGET="$OUTPUT_DIR/mise-asdf.yaml"

write_empty_yaml() {
  local tmp
  tmp="$(mktemp "$OUTPUT_DIR/.mise-asdf.yaml.XXXXXX")"
  {
    printf '%s\n' '# Generated by tools/discovery/scripts/50-mise-asdf.sh'
    printf '%s\n' '# No mise or asdf detected on this machine.'
    printf '\n'
    printf '%s\n' 'tools: {}'
  } > "$tmp"
  mv "$tmp" "$TARGET"
}

# Format JSON-style flow list of versions: ["a", "b", "c"]
format_versions_flow() {
  local versions="$1"
  if [ -z "$versions" ]; then
    printf '[]'
    return 0
  fi
  local first=1
  printf '['
  while IFS= read -r v; do
    [ -z "$v" ] && continue
    if [ "$first" -eq 1 ]; then
      first=0
    else
      printf ', '
    fi
    printf '"%s"' "$v"
  done <<< "$versions"
  printf ']'
}

emit_yaml() {
  # $1 = path to a temp dir holding per-tool data files:
  #   $tmpdir/tools.list  - newline list of tool names (will be sorted)
  #   $tmpdir/<tool>.installed - sorted versions, one per line
  #   $tmpdir/<tool>.current   - resolved version (single line) or empty
  local tmpdir="$1"
  local source_label="$2"
  local tmp
  tmp="$(mktemp "$OUTPUT_DIR/.mise-asdf.yaml.XXXXXX")"
  {
    printf '%s\n' '# Generated by tools/discovery/scripts/50-mise-asdf.sh'
    printf '%s\n' "# Detected via $source_label."
    printf '\n'

    if [ ! -s "$tmpdir/tools.list" ]; then
      printf '%s\n' 'tools: {}'
    else
      printf '%s\n' 'tools:'
      local tools_sorted
      tools_sorted="$(LC_ALL=C sort -u "$tmpdir/tools.list")"
      while IFS= read -r tool; do
        [ -z "$tool" ] && continue
        local installed_versions=""
        local current_version=""
        if [ -f "$tmpdir/$tool.installed" ]; then
          installed_versions="$(LC_ALL=C sort -u "$tmpdir/$tool.installed" | sed '/^[[:space:]]*$/d')"
        fi
        if [ -f "$tmpdir/$tool.current" ]; then
          current_version="$(sed -n '1p' "$tmpdir/$tool.current" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        fi
        printf '  %s:\n' "$tool"
        printf '    installed: '
        format_versions_flow "$installed_versions"
        printf '\n'
        if [ -z "$current_version" ]; then
          printf '    in_use: null\n'
        else
          printf '    in_use: "%s"\n' "$current_version"
        fi
        printf '    tags: [TODO]\n'
      done <<< "$tools_sorted"
    fi
  } > "$tmp"
  mv "$tmp" "$TARGET"
}

collect_mise() {
  local tmpdir
  tmpdir="$(mktemp -d "$OUTPUT_DIR/.mise-asdf-work.XXXXXX")"
  : > "$tmpdir/tools.list"

  log_info "collecting mise installed versions"
  local list_raw=""
  local used_json=0
  if mise ls --json >/dev/null 2>&1; then
    if list_raw="$(mise ls --json 2>/dev/null)"; then
      used_json=1
    fi
  fi

  if [ "$used_json" -eq 1 ] && command -v python3 >/dev/null 2>&1; then
    # Parse JSON with python3. mise ls --json shape:
    #   { "tool": [ { "version": "x", "requested_version": "...", "active": true|false, ... }, ... ], ... }
    # Extract installed versions and the active one.
    if ! printf '%s' "$list_raw" | python3 - "$tmpdir" <<'PY'
import json, os, sys
tmpdir = sys.argv[1]
data = json.load(sys.stdin)
tools_path = os.path.join(tmpdir, "tools.list")
with open(tools_path, "w") as tf:
    for tool, entries in (data or {}).items():
        if not isinstance(entries, list):
            continue
        tf.write(tool + "\n")
        installed = []
        active = None
        for e in entries:
            if not isinstance(e, dict):
                continue
            v = e.get("version")
            if v:
                installed.append(str(v))
            if e.get("active") and v and active is None:
                active = str(v)
        with open(os.path.join(tmpdir, tool + ".installed"), "w") as f:
            for v in installed:
                f.write(v + "\n")
        if active is not None:
            with open(os.path.join(tmpdir, tool + ".current"), "w") as f:
                f.write(active + "\n")
PY
    then
      log_warn "failed to parse mise ls --json; falling back to text parse"
      used_json=0
    fi
  fi

  if [ "$used_json" -eq 0 ]; then
    log_info "parsing mise ls text output"
    local text_raw
    if ! text_raw="$(mise ls 2>/dev/null)"; then
      text_raw=""
    fi
    # Lines look like: "tool  version  source"
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      # Skip header-like lines
      case "$line" in
        Plugin*|Tool*) continue;;
      esac
      local tool version
      tool="$(printf '%s' "$line" | awk '{print $1}')"
      version="$(printf '%s' "$line" | awk '{print $2}')"
      [ -z "$tool" ] && continue
      [ -z "$version" ] && continue
      # Avoid duplicate tool lines in tools.list (sort -u handles it later)
      printf '%s\n' "$tool" >> "$tmpdir/tools.list"
      printf '%s\n' "$version" >> "$tmpdir/$tool.installed"
    done <<< "$text_raw"

    log_info "parsing mise current"
    local current_raw
    if ! current_raw="$(mise current 2>/dev/null)"; then
      current_raw=""
    fi
    # Lines look like: "tool version"
    while IFS= read -r line; do
      [ -z "$line" ] && continue
      local tool version
      tool="$(printf '%s' "$line" | awk '{print $1}')"
      version="$(printf '%s' "$line" | awk '{print $2}')"
      [ -z "$tool" ] && continue
      [ -z "$version" ] && continue
      printf '%s\n' "$version" > "$tmpdir/$tool.current"
    done <<< "$current_raw"
  fi

  emit_yaml "$tmpdir" "mise ls / mise current"
  rm -rf "$tmpdir"
}

collect_asdf() {
  local tmpdir
  tmpdir="$(mktemp -d "$OUTPUT_DIR/.mise-asdf-work.XXXXXX")"
  : > "$tmpdir/tools.list"

  log_info "collecting asdf installed versions"
  local list_raw=""
  if ! list_raw="$(asdf list 2>/dev/null)"; then
    list_raw=""
  fi
  # `asdf list` output groups by plugin. Plugin names are flush-left lines
  # ending with no leading whitespace; versions are indented.
  local current_tool=""
  while IFS= read -r raw; do
    [ -z "$raw" ] && continue
    case "$raw" in
      \ *|$'\t'*)
        # Indented version line
        if [ -n "$current_tool" ]; then
          local v
          v="$(printf '%s' "$raw" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | awk '{print $1}' | sed 's/^\*//')"
          [ -n "$v" ] && printf '%s\n' "$v" >> "$tmpdir/$current_tool.installed"
        fi
        ;;
      *)
        current_tool="$(printf '%s' "$raw" | awk '{print $1}')"
        [ -n "$current_tool" ] && printf '%s\n' "$current_tool" >> "$tmpdir/tools.list"
        ;;
    esac
  done <<< "$list_raw"

  log_info "collecting asdf current"
  local current_raw
  if ! current_raw="$(asdf current 2>/dev/null)"; then
    current_raw=""
  fi
  # Format: "tool  version  source"  (version may be "______" / "No version")
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    case "$line" in
      Name*) continue;;
    esac
    local tool version
    tool="$(printf '%s' "$line" | awk '{print $1}')"
    version="$(printf '%s' "$line" | awk '{print $2}')"
    [ -z "$tool" ] && continue
    case "$version" in
      ""|"______"|"No"|"-"|"missing")
        continue
        ;;
    esac
    printf '%s\n' "$version" > "$tmpdir/$tool.current"
  done <<< "$current_raw"

  emit_yaml "$tmpdir" "asdf list / asdf current"
  rm -rf "$tmpdir"
}

if command -v mise >/dev/null 2>&1; then
  log_info "mise detected"
  collect_mise
  log_ok "wrote $TARGET (via mise)"
elif command -v asdf >/dev/null 2>&1; then
  log_info "asdf detected"
  collect_asdf
  log_ok "wrote $TARGET (via asdf)"
else
  log_skip "neither mise nor asdf installed"
  write_empty_yaml
  log_ok "wrote $TARGET (empty)"
fi
